markdown: rdiscount
permalink: /:title/
baseurl: /blog
url: http://b-bicycle.github.io/blog
name: B_B Blog
author: B_B
qq: 875284899
email: 875284899@qq.com
duoshuo: 
beian: 粤ICP
cnzz: 119959
weibo: 
github: bb66
pygments: true
safe: true
paginate: 20
about: "这里是 B_B 的个人博客，创建于 2013 年。使用 Jekyll @ GitHub。<br />"

