markdown: rdiscount
permalink: /:title/
baseurl: /blog
url: http://bb66.github.io/blog
name: bb66.github.io
author: B_B
qq: 875284899
email: 875284899@qq.com
duoshuo: 
beian: gz
cnzz: 119959
weibo: b_b
github: bb66
pygments: true
safe: true
paginate: 20
about: "这里是 B_B 的个人博客，创建于 2013 年。使用 Jekyll @ GitHub。<br />"

